# Generated by Django 5.0 on 2023-12-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
